# Site settings
author: Jessica Rowland
title: 
header-img: img/home-bg.png
email: rowlandjl@vcu.edu
copyright_name: Jessica Rowland
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jesssicarowland
github_username:  rowlandjl

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
